language: go
go: '1.13'
script:
- scripts/build.sh --release
- scripts/test.sh -race -coverprofile=coverage.txt -covermode=atomic
- scripts/vet.sh
after_success:
- scripts/travis-release.sh
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: Nyj6y6NJdtTMs/5h4Pj5uORmT/Yaq7XeSyRUkjLjD3K/auElmkp5J4+ip+2f/2EnwHp7rFNclRzyIEhQa4V3hUqiu+AhBhFuBwD+lkJGMG4OwyUafF5kL1qfInjEBpIDOlWlJ+tADu34IvmHSM0Ux1OgssSecFRb5FJRcPzPrn4wtXeBTCyjk5xoxbVnDyHdu1x6FNEUEIU7HwE4l2YQ8WUnXswbt5LTYnOkx6eUDzMBjkRxGLIuyJmnc+ryK0+x6FtP1hG/BUUUvsXaqY7VPTtN9duuAXRrgPjN5DeMMkL/4LG2hEH8XmwWuaIxDWFUxemCyVSo2EegtFBjvlh994+3XnmIdB6Wo0PJBU/S3J1sYcfBnVlG5P+xMRNS9oBIXzJzSV4wXGP6kk+LUqzwsbk8ltCWzyMcuDY7EL1Jl+vbmIAZ15hkJ/hLFioFrxX6ERdp67KrKncIs2Hx0SoFvf49J033cp1xjI90RzR446Gdn/JHf0IV58cm1g9ONgbjO7XiyubZ27UcGKlaVYfLCRFZaSgvKdBLxVaEXxeqeMCwVQrAsYkZAtFm+4RgYTwAivlMY+Z85mQpNmw1BDal7HYaGviiJX2x0ppO2wa++tdBq2EUdu1kxzxvmVLcQogFfe7kR7PcK97yevAb0hKU3tS3PR7KHYYsphU5Ka5Qhlg=
