# Travis Encryption keys: https://docs.travis-ci.com/user/encryption-keys/#encryption-scheme
# Travis Best Security Practices: https://docs.travis-ci.com/user/best-practices-security#recommendations-on-how-to-avoid-leaking-secrets-to-build-logs
# Travis conditional releases: https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
#
# only build if tag is blank to prevent infinit loops 
#   git push => travis ci build => build tag => travis ci build => ...
if: branch = master AND tag IS blank
language: go
go: '1.13'
script:
- scripts/build.sh --release
- scripts/test.sh -race -coverprofile=coverage.txt -covermode=atomic
- scripts/vet.sh
after_success:
- scripts/travis-release.sh
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: JaEND3UzsETxaUht6qjrR+vNTZTMNz9d37WLUW33WERIloGQjkHbH5j7czbchwaL2nwkavxehpjyw9bkyISVInHwVjEq52XpZdnhPyrwwBFa7FaoiBaue1MD/bFpJcxkBCzKqvXiRT0AI4yznaISF7PBCMayDhrzd9ISfu7cWtacasowa0MTjaXCAY42Ygh7JUwHoSozUF52SsnNqJX3pjOSViekgB2EQbEC0pWoxIcKmhAn4qIWz5A3kFsK1VD23BX9WuKFUHbDR9hoMeaFLjefhaxmh7Ar0Dzu1F9ew4YdKZc1mZ0GD4bOdw8u/zAedlxwWK7pRYzYSxjRSZnCBlVdKOuoJ4te8o8OuVfek30cJ5rs9KtLkwfCIyCg7QxgSo9KvODzN/KpOsYNM0dNgXOvHnXBzQMt4yTA0frmCHrXDQODkPNgbhck7Uw4EK5bn9+6RAw+HSjuJlYR75zMIOxLcUPhT7VYh2cYpeuw18V9rJuoS7E+SRajsFi0egBOzplZg0oBVsrtUwU3t1pOApK/2xkGqyTq3SMwSyYysavUVUKik2Qcq53aXnag7ALeHvXSRf8Th6LPEl5R7cQoB0s5oV+mA512MMlLPaU/398Ekzi/Yhv8VzCbHGUHFu1F+i/2pBy7zGhTQzQF8XkyAcAA9b/v0WLOt1O15J/xzWY=
